let order = false;
let users = [
    {
        numerics: '',
        firstName: "Rokas",
        lastName: "Skinderis",
        age: "28",
        gender: "male",
        city: "Kaunas",
        workplace: "",
        hobby: "Interacting with his dog",
        height: "194",
        codingSkill: "???? invalidErroR",
    },
    {
        firstName: "Mindaugas",
        lastName: "Straksys",
        age: "22",
        gender: "male",
        city: "Kaunas",
        workplace: "",
        hobby: "Skydiving",
        height: "176",
        codingSkill: "5",
    },
    {
        firstName: "Zilvinas",
        lastName: "Pusnys",
        age: "30",
        gender: "male",
        city: "Kaunas",
        workplace: "",
        hobby: "Napping",
        height: "175",
        codingSkill: "5",
    },
    {
        firstName: "Ieva",
        lastName: "Staseviciute",
        age: "33",
        gender: "female",
        city: "Vilnius",
        workplace: "",
        hobby: "Riding a motorcycle",
        height: "174",
        codingSkill: "3",
    },
    {
        firstName: "Eimantas",
        lastName: "Jurenkovas",
        age: "49",
        gender: "male",
        city: "Ukmerge",
        workplace: "",
        hobby: "Fishing",
        height: "172",
        codingSkill: "2",
    },
    {
        firstName: "Simona",
        lastName: "Sleviene",
        age: "30",
        gender: "female",
        city: "Siauliai",
        workplace: "",
        hobby: "Knitting toys",
        height: "170",
        codingSkill: "4",
    },
    {
        firstName: "Rokas",
        lastName: "Virvicius",
        age: "27",
        gender: "male",
        city: "Vilnius",
        workplace: "",
        hobby: "Basketball",
        height: "185",
        codingSkill: "3",
    },
    {
        firstName: "Roman",
        lastName: "Laskov",
        age: "34",
        gender: "male",
        city: "Kaunas",
        workplace: "",
        hobby: "Sports",
        height: "197",
        codingSkill: "3",
    },
    {
        firstName: "Eimantas",
        lastName: "Riauba",
        age: "28",
        gender: "male",
        city: "",
        workplace: "",
        hobby: "Riding Porsche",
        height: "218",
        codingSkill: "3",
    },
    {
        firstName: "Aurimas",
        lastName: "Gaidelis",
        age: "25",
        gender: "male",
        city: "",
        workplace: "",
        hobby: "Playing video games on a modern personal computer (PC). Most likely using keyboard and mouse for control. For certain games controller is an option.",
        height: "182",
        codingSkill: "5",
    },
    {
        firstName: "Karolis",
        lastName: "Krisciunas",
        age: "29",
        gender: "male",
        city: "",
        workplace: "",
        hobby: "Building a Family",
        height: "179",
        codingSkill: "3",
    },
    {
        firstName: "Mantas",
        lastName: "Dargis",
        age: "24",
        gender: "male",
        city: "Vilnius",
        workplace: "",
        hobby: "Playing with kids in the Sandbox",
        height: "182",
        codingSkill: "3",
    },
    {
        firstName: "Vytautas",
        lastName: "Jakavickis",
        age: "27",
        gender: "male",
        city: "",
        workplace: "",
        hobby: "House Chores",
        height: "172",
        codingSkill: "2",
    },
    {
        firstName: "Tatjana",
        lastName: "Volodko",
        age: "32",
        gender: "female",
        city: "",
        workplace: "",
        hobby: "Baking Children",
        height: "150",
        codingSkill: "2",
    },
    {
        firstName: "Rimvydas",
        lastName: "Linkevicius",
        age: "54",
        gender: "male",
        city: "Klaipeda",
        workplace: "",
        hobby: "Music",
        height: "171",
        codingSkill: "2",
    },
    {
        firstName: "Edvinas",
        lastName: "Stanionis",
        age: "21",
        gender: "male",
        city: "",
        workplace: "",
        hobby: "Chasing Girls",
        height: "174",
        codingSkill: "2",
    },
    {
        firstName: "Alicija",
        lastName: "Gruode",
        age: "29",
        gender: "female",
        city: "",
        workplace: "",
        hobby: "American Football",
        height: "165",
        codingSkill: "2",
    },
    {
        firstName: "Margarita",
        lastName: "Budryte",
        age: "24",
        gender: "female",
        city: "Vilnius",
        workplace: "",
        hobby: "Clubbing",
        height: "175",
        codingSkill: "2",
    },
    {
        firstName: "Gabriele",
        lastName: "Biveiniene",
        age: "31",
        gender: "female",
        city: "",
        workplace: "",
        hobby: "Telling her spouse what to do",
        height: "160",
        codingSkill: "2",
    },
    {
        firstName: "Giedre",
        lastName: "Lukosiuniene",
        age: "27",
        gender: "female",
        city: "",
        workplace: "",
        hobby:"Pletkininkavimas",
        height: "172",
        codingSkill: "2",
    },
];
let usersReset = users;