let order = false;
let users = [
    {
        numerics: '',
        firstName: "Rokas",
        lastName: "Skinderis",
        age: 28,
        gender: "male",
        hobby: "Interacting with his dog",
        height: 194,
        codingSkill: "???? invalidErroR",
    },
    {
        firstName: "Mindaugas",
        lastName: "Straksys",
        age: 22,
        gender: "male",
        hobby: "Skydiving",
        height: 176,
        codingSkill: 5,
    },
    {
        firstName: "Zilvinas",
        lastName: "Pusnys",
        age: 30,
        gender: "male",
        hobby: "Napping",
        height: 175,
        codingSkill: 5,
    },
    {
        firstName: "Ieva",
        lastName: "Staseviciute",
        age: 33,
        gender: "female",
        hobby: "Riding a motorcycle",
        height: 174,
        codingSkill: 3,
    },
    {
        firstName: "Eimantas",
        lastName: "Jurenkovas",
        age: 49,
        gender: "male",
        hobby: "Fishing",
        height: 172,
        codingSkill: 2,
    },
    {
        firstName: "Simona",
        lastName: "Sleviene",
        age: 30,
        gender: "female",
        hobby: "Knitting toys",
        height: 170,
        codingSkill: 4,
    },
    {
        firstName: "Rokas",
        lastName: "Virvicius",
        age: 27,
        gender: "male",
        hobby: "Basketball",
        height: 185,
        codingSkill: 3,
    },
    {
        firstName: "Roman",
        lastName: "Laskov",
        age: 34,
        gender: "male",
        hobby: "Sports",
        height: 197,
        codingSkill: 3,
    },
    {
        firstName: "Eimantas",
        lastName: "Riauba",
        age: 28,
        gender: "male",
        hobby: "Riding Porsche",
        height: 218,
        codingSkill: 3,
    },
    {
        firstName: "Aurimas",
        lastName: "Gaidelis",
        age: 25,
        gender: "male",
        hobby: "Reading the Bible",
        height: 170,
        codingSkill: 5,
    },
    {
        firstName: "Karolis",
        lastName: "Krisciunas",
        age: 29,
        gender: "male",
        hobby: "Building a Family",
        height: 179,
        codingSkill: 3,
    },
    {
        firstName: "Mantas",
        lastName: "Dargis",
        age: 24,
        gender: "male",
        hobby: "Playing with kids in the Sandbox",
        height: 182,
        codingSkill: 3,
    },
    {
        firstName: "Vytautas",
        lastName: "Jakavickis",
        age: 27,
        gender: "male",
        hobby: "House Chores",
        height: 172,
        codingSkill: 2,
    },
    {
        firstName: "Tatjana",
        lastName: "Volodko",
        age: 32,
        gender: "female",
        hobby: "Baking Children",
        height: 150,
        codingSkill: 2,
    },
    {
        firstName: "Rimvydas",
        lastName: "Linkevicius",
        age: 34,
        gender: "male",
        hobby: "Running from Cops",
        height: 189,
        codingSkill: 3,
    },
    {
        firstName: "Edvinas",
        lastName: "Stanionis",
        age: 21,
        gender: "male",
        hobby: "Chasing Girls",
        height: 174,
        codingSkill: 2,
    },
    {
        firstName: "Alicija",
        lastName: "Gruode",
        age: 29,
        gender: "female",
        hobby: "American Football",
        height: 165,
        codingSkill: 2,
    },
    {
        firstName: "Margarita",
        lastName: "Budryte",
        age: 24,
        gender: "female",
        hobby: "Clubbing",
        height: 175,
        codingSkill: 2,
    },
    {
        firstName: "Gabriele",
        lastName: "Biveiniene",
        age: 31,
        gender: "female",
        hobby: "Telling her spouse what to do",
        height: 168,
        codingSkill: 2,
    },
    {
        firstName: "Giedre",
        lastName: "Lukosiuniene",
        age: 27,
        gender: "female",
        hobby: "Pletkininkavimas",
        height: 172,
        codingSkill: 2,
    },
];
const usersReset = users;